DROP TABLE IF EXISTS subject_teacher;
DROP TABLE IF EXISTS subject_group;
DROP TABLE IF EXISTS teachers;
DROP TABLE IF EXISTS students;
DROP TABLE IF EXISTS groups;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS subjects;

CREATE TABLE users (
                       id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                       login varchar(30) NOT NULL ,
                       email varchar(60) NOT NULL UNIQUE ,
                       role varchar(30) NOT NULL ,
                       password varchar(100) NOT NULL
);

CREATE TABLE subjects (
                          id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                          title varchar(100) NOT NULL ,
                          type varchar(30) NOT NULL ,
                          teacher varchar(100) NOT NULL
);

CREATE TABLE groups (
                        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                        number int NOT NULL,
                        year_of_admission int NOT NULL
);

CREATE TABLE teachers (
                          id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                          full_name varchar(100) NOT NULL ,
                          login varchar(30) NOT NULL ,
                          users_id int REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE students (
                          id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                          full_name varchar(100) NOT NULL ,
                          group_name int NOT NULL ,
                          login varchar(30) NOT NULL ,
                          users_id int UNIQUE REFERENCES users(id) ,
                          group_id int UNIQUE REFERENCES groups(id)
);

-- CREATE TABLE attestation_student (
--     attestation_id int REFERENCES
-- )

CREATE TABLE subject_teacher (
                                 subject_id int UNIQUE REFERENCES subjects(id) ,
                                 teacher_id int UNIQUE REFERENCES teachers(id) ,
                                 CONSTRAINT subject_teacher_pkey PRIMARY KEY (subject_id, teacher_id)
);

CREATE TABLE subject_group (
                               subject_id int UNIQUE REFERENCES subjects(id) ,
                               groups_id int UNIQUE REFERENCES groups(id) ,
                               CONSTRAINT subject_group_pkey PRIMARY KEY (subject_id, groups_id)
)

